"use server";

import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { DoodleStroke } from "./heroDoodles";

// Dev-only: persist the current hero doodles into heroDoodles.ts as the new
// default. Writes a source file, so it only works while running locally.
export async function saveHeroDoodles(strokes: DoodleStroke[]) {
  if (process.env.NODE_ENV === "production") {
    return { success: false as const, error: "Disabled in production." };
  }

  const round = (n: number) => Math.round(n * 10000) / 10000;
  const cleaned: DoodleStroke[] = strokes.map((s) => ({
    color: s.color,
    anchor: s.anchor ?? "canvas",
    points: s.points.map(([x, y]) => [round(x), round(y)] as [number, number]),
  }));

  const file = path.join(process.cwd(), "app/components/heroDoodles.ts");
  const contents = `// Default marker doodles drawn behind the hero so the canvas isn't blank.
// Each stroke is tied to an anchor element ("heading", "tower") so it tracks
// that element as the layout reflows; "canvas" strokes map to the whole hero.
// This file is regenerated by the hero's dev-only "Save as default" button.

export type DoodleAnchor = "heading" | "tower" | "canvas";

// \`points\` are normalized (0–1) within the anchor element's bounding box
// (values may fall slightly outside 0–1 for strokes just beside/below it).
// Missing anchor = legacy stroke normalized to the whole canvas.
export type DoodleStroke = {
  color: string;
  anchor?: DoodleAnchor;
  points: [number, number][];
};

export const HERO_DOODLES: DoodleStroke[] = ${JSON.stringify(cleaned)};
`;

  await writeFile(file, contents, "utf8");
  return { success: true as const, count: cleaned.length };
}
